//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pms.FileWatcher.WinService.TransactionRouterServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pms.transactionrouter/11/08", ConfigurationName="TransactionRouterServiceRef.ITransactionRouter")]
    public interface ITransactionRouter {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://pms.transactionrouter/11/08/ITransactionRouter/SubmitTransactionFile")]
        void SubmitTransactionFile(Pms.Framework.Domain.TransactionFileItem transactionFile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransactionRouterChannel : Pms.FileWatcher.WinService.TransactionRouterServiceRef.ITransactionRouter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionRouterClient : System.ServiceModel.ClientBase<Pms.FileWatcher.WinService.TransactionRouterServiceRef.ITransactionRouter>, Pms.FileWatcher.WinService.TransactionRouterServiceRef.ITransactionRouter {
        
        public TransactionRouterClient() {
        }
        
        public TransactionRouterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionRouterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionRouterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionRouterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SubmitTransactionFile(Pms.Framework.Domain.TransactionFileItem transactionFile) {
            base.Channel.SubmitTransactionFile(transactionFile);
        }
    }
}
