//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pms.ManageWorkspaces.UI.Controls.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pms.ManageWorkspaces.UI.Controls.Localization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image.
        /// </summary>
        public static string WorkspaceBrowser_AddItem_AddImage {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_AddItem_AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string WorkspaceBrowser_AddItem_Cancel {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_AddItem_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string WorkspaceBrowser_AddItem_Name {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_AddItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of the item.
        /// </summary>
        public static string WorkspaceBrowser_AddItem_OI {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_AddItem_OI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string WorkspaceBrowser_AddItem_OK {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_AddItem_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent of item.
        /// </summary>
        public static string WorkspaceBrowser_AddItem_POI {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_AddItem_POI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string WorkspaceBrowser_AddItem_Type {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_AddItem_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string WorkspaceBrowser_AddWorkspace {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_AddWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string WorkspaceBrowser_btn_Cancel {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string WorkspaceBrowser_btn_OK {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Window.
        /// </summary>
        public static string WorkspaceBrowser_DescriptionWindow {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_DescriptionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Item.
        /// </summary>
        public static string WorkspaceBrowser_ModifyItem {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_ModifyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string WorkspaceBrowser_MV_Add {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_MV_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string WorkspaceBrowser_MV_Back {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_MV_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        public static string WorkspaceBrowser_MV_btnAddFav {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_MV_btnAddFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string WorkspaceBrowser_MV_btnAddItem {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_MV_btnAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail View.
        /// </summary>
        public static string WorkspaceBrowser_MV_btnDV {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_MV_btnDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View.
        /// </summary>
        public static string WorkspaceBrowser_MV_btnLV {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_MV_btnLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree View.
        /// </summary>
        public static string WorkspaceBrowser_MV_btnTV {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_MV_btnTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in New tab.
        /// </summary>
        public static string WorkspaceBrowser_MV_btnVNT {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_MV_btnVNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        public static string WorkspaceBrowser_MV_Navigate {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_MV_Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string WorkspaceBrowser_MV_Tab_Home {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_MV_Tab_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string WorkspaceBrowser_MV_View {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_MV_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigator Window.
        /// </summary>
        public static string WorkspaceBrowser_NavigatorWindow {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_NavigatorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string WorkspaceBrowser_PopUpListView_ApplicationName {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_PopUpListView_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties Window.
        /// </summary>
        public static string WorkspaceBrowser_PropertiesWindow {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_PropertiesWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Libraries.
        /// </summary>
        public static string WorkspaceBrowser_SC_SearchText {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_SC_SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Preferences.
        /// </summary>
        public static string WorkspaceBrowser_Tab_UP {
            get {
                return ResourceManager.GetString("WorkspaceBrowser_Tab_UP", resourceCulture);
            }
        }
    }
}
