//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace Broobu.LATI.Contract.Domain.W3C {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/poi")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/poi", IsNullable=false)]
    public partial class pois : POIType {
        
        private poi[] poiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("poi")]
        public poi[] poi {
            get {
                return this.poiField;
            }
            set {
                this.poiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/poi")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/poi", IsNullable=false)]
    public partial class poi : POIType {
        
        private location locationField;
        
        /// <remarks/>
        public location location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/poi")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/poi", IsNullable=false)]
    public partial class location : POIBaseType {
        
        private point[] pointField;
        
        private line[] lineField;
        
        private polygon[] polygonField;
        
        private POIBaseType addressField;
        
        private string undeterminedField;
        
        private relationship[] relationshipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("point")]
        public point[] point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("line")]
        public line[] line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("polygon")]
        public polygon[] polygon {
            get {
                return this.polygonField;
            }
            set {
                this.polygonField = value;
            }
        }
        
        /// <remarks/>
        public POIBaseType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string undetermined {
            get {
                return this.undeterminedField;
            }
            set {
                this.undeterminedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relationship")]
        public relationship[] relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/poi")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/poi", IsNullable=false)]
    public partial class point : POITermType {
        
        private GML_CE_Geometry pointField;
        
        /// <remarks/>
        public GML_CE_Geometry Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/poi")]
    public partial class GML_CE_Geometry {
        
        private string posListField;
        
        private string srsNameField;
        
        public GML_CE_Geometry() {
            this.srsNameField = "http://www.opengis.net/def/crs/EPSG/0/4326";
        }
        
        /// <remarks/>
        public string posList {
            get {
                return this.posListField;
            }
            set {
                this.posListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("http://www.opengis.net/def/crs/EPSG/0/4326")]
        public string srsName {
            get {
                return this.srsNameField;
            }
            set {
                this.srsNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/poi")]
    [System.Xml.Serialization.XmlRootAttribute("label", Namespace="http://www.w3.org/poi", IsNullable=false)]
    public partial class POITermType : POIBaseType {
        
        private string termField;
        
        private string schemeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POIType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POITermType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/poi")]
    [System.Xml.Serialization.XmlRootAttribute("description", Namespace="http://www.w3.org/poi", IsNullable=false)]
    public partial class POIBaseType {
        
        private string valueField;
        
        private POITermType authorField;
        
        private POITermType licenseField;
        
        private string[] textField;
        
        private string idField;
        
        private string hrefField;
        
        private string typeField;
        
        private System.DateTime createdField;
        
        private bool createdFieldSpecified;
        
        private System.DateTime updatedField;
        
        private bool updatedFieldSpecified;
        
        private System.DateTime deletedField;
        
        private bool deletedFieldSpecified;
        
        private string langField;
        
        private string baseField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public POITermType author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public POITermType license {
            get {
                return this.licenseField;
            }
            set {
                this.licenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatedSpecified {
            get {
                return this.updatedFieldSpecified;
            }
            set {
                this.updatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deletedSpecified {
            get {
                return this.deletedFieldSpecified;
            }
            set {
                this.deletedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string @base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/poi")]
    public abstract partial class POIType : POIBaseType {
        
        private POITermType[] labelField;
        
        private POIBaseType[] descriptionField;
        
        private POITermType[] categoryField;
        
        private POITermType[] timeField;
        
        private POITermType[] linkField;
        
        private string metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("label")]
        public POITermType[] label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public POIBaseType[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("category")]
        public POITermType[] category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("time")]
        public POITermType[] time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public POITermType[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public string metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/poi")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/poi", IsNullable=false)]
    public partial class line : POITermType {
        
        private GML_CE_Geometry lineStringField;
        
        /// <remarks/>
        public GML_CE_Geometry LineString {
            get {
                return this.lineStringField;
            }
            set {
                this.lineStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/poi")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/poi", IsNullable=false)]
    public partial class polygon : POITermType {
        
        private GML_CE_Geometry simplePolygonField;
        
        /// <remarks/>
        public GML_CE_Geometry SimplePolygon {
            get {
                return this.simplePolygonField;
            }
            set {
                this.simplePolygonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/poi")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/poi", IsNullable=false)]
    public partial class relationship : POITermType {
        
        private string targetPOIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string targetPOI {
            get {
                return this.targetPOIField;
            }
            set {
                this.targetPOIField = value;
            }
        }
    }
}
