//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.SimpleDb.Adapter.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", ConfigurationName="ServiceRef.AmazonSDBPortType")]
    public interface AmazonSDBPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="CreateDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Iris.SimpleDb.Adapter.ServiceRef.CreateDomainResponse1 CreateDomain(Iris.SimpleDb.Adapter.ServiceRef.CreateDomainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ListDomains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Iris.SimpleDb.Adapter.ServiceRef.ListDomainsResponse1 ListDomains(Iris.SimpleDb.Adapter.ServiceRef.ListDomainsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DomainMetadata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Iris.SimpleDb.Adapter.ServiceRef.DomainMetadataResponse1 DomainMetadata(Iris.SimpleDb.Adapter.ServiceRef.DomainMetadataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DeleteDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Iris.SimpleDb.Adapter.ServiceRef.DeleteDomainResponse1 DeleteDomain(Iris.SimpleDb.Adapter.ServiceRef.DeleteDomainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PutAttributes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Iris.SimpleDb.Adapter.ServiceRef.PutAttributesResponse1 PutAttributes(Iris.SimpleDb.Adapter.ServiceRef.PutAttributesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BatchPutAttributes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Iris.SimpleDb.Adapter.ServiceRef.BatchPutAttributesResponse1 BatchPutAttributes(Iris.SimpleDb.Adapter.ServiceRef.BatchPutAttributesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetAttributes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Iris.SimpleDb.Adapter.ServiceRef.GetAttributesResponse1 GetAttributes(Iris.SimpleDb.Adapter.ServiceRef.GetAttributesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DeleteAttributes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Iris.SimpleDb.Adapter.ServiceRef.DeleteAttributesResponse1 DeleteAttributes(Iris.SimpleDb.Adapter.ServiceRef.DeleteAttributesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="BatchDeleteAttributes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Iris.SimpleDb.Adapter.ServiceRef.BatchDeleteAttributesResponse1 BatchDeleteAttributes(Iris.SimpleDb.Adapter.ServiceRef.BatchDeleteAttributesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Iris.SimpleDb.Adapter.ServiceRef.SelectResponse1 Select(Iris.SimpleDb.Adapter.ServiceRef.SelectRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class CreateDomain : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string domainNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
                this.RaisePropertyChanged("DomainName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private Attribute[] attributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute", Order=1)]
        public Attribute[] Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
                this.RaisePropertyChanged("Attribute");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class Attribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class DeleteableItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemNameField;
        
        private Attribute[] attributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
                this.RaisePropertyChanged("ItemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute", Order=1)]
        public Attribute[] Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
                this.RaisePropertyChanged("Attribute");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class ReplaceableItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemNameField;
        
        private ReplaceableAttribute[] attributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
                this.RaisePropertyChanged("ItemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute", Order=1)]
        public ReplaceableAttribute[] Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
                this.RaisePropertyChanged("Attribute");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class ReplaceableAttribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        private bool replaceField;
        
        public ReplaceableAttribute() {
            this.replaceField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Replace {
            get {
                return this.replaceField;
            }
            set {
                this.replaceField = value;
                this.RaisePropertyChanged("Replace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class UpdateCondition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        private bool existsField;
        
        public UpdateCondition() {
            this.existsField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
                this.RaisePropertyChanged("Exists");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class CreateDomainResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
                this.RaisePropertyChanged("ResponseMetadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class ResponseMetadata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdField;
        
        private string boxUsageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BoxUsage {
            get {
                return this.boxUsageField;
            }
            set {
                this.boxUsageField = value;
                this.RaisePropertyChanged("BoxUsage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDomainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.CreateDomain CreateDomain;
        
        public CreateDomainRequest() {
        }
        
        public CreateDomainRequest(Iris.SimpleDb.Adapter.ServiceRef.CreateDomain CreateDomain) {
            this.CreateDomain = CreateDomain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDomainResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.CreateDomainResponse CreateDomainResponse;
        
        public CreateDomainResponse1() {
        }
        
        public CreateDomainResponse1(Iris.SimpleDb.Adapter.ServiceRef.CreateDomainResponse CreateDomainResponse) {
            this.CreateDomainResponse = CreateDomainResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class ListDomains : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int maxNumberOfDomainsField;
        
        private bool maxNumberOfDomainsFieldSpecified;
        
        private string nextTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MaxNumberOfDomains {
            get {
                return this.maxNumberOfDomainsField;
            }
            set {
                this.maxNumberOfDomainsField = value;
                this.RaisePropertyChanged("MaxNumberOfDomains");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxNumberOfDomainsSpecified {
            get {
                return this.maxNumberOfDomainsFieldSpecified;
            }
            set {
                this.maxNumberOfDomainsFieldSpecified = value;
                this.RaisePropertyChanged("MaxNumberOfDomainsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NextToken {
            get {
                return this.nextTokenField;
            }
            set {
                this.nextTokenField = value;
                this.RaisePropertyChanged("NextToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class ListDomainsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ListDomainsResult listDomainsResultField;
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ListDomainsResult ListDomainsResult {
            get {
                return this.listDomainsResultField;
            }
            set {
                this.listDomainsResultField = value;
                this.RaisePropertyChanged("ListDomainsResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
                this.RaisePropertyChanged("ResponseMetadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class ListDomainsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] domainNameField;
        
        private string nextTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DomainName", Order=0)]
        public string[] DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
                this.RaisePropertyChanged("DomainName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NextToken {
            get {
                return this.nextTokenField;
            }
            set {
                this.nextTokenField = value;
                this.RaisePropertyChanged("NextToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListDomainsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.ListDomains ListDomains;
        
        public ListDomainsRequest() {
        }
        
        public ListDomainsRequest(Iris.SimpleDb.Adapter.ServiceRef.ListDomains ListDomains) {
            this.ListDomains = ListDomains;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListDomainsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.ListDomainsResponse ListDomainsResponse;
        
        public ListDomainsResponse1() {
        }
        
        public ListDomainsResponse1(Iris.SimpleDb.Adapter.ServiceRef.ListDomainsResponse ListDomainsResponse) {
            this.ListDomainsResponse = ListDomainsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class DomainMetadata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string domainNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
                this.RaisePropertyChanged("DomainName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class DomainMetadataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DomainMetadataResult domainMetadataResultField;
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DomainMetadataResult DomainMetadataResult {
            get {
                return this.domainMetadataResultField;
            }
            set {
                this.domainMetadataResultField = value;
                this.RaisePropertyChanged("DomainMetadataResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
                this.RaisePropertyChanged("ResponseMetadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class DomainMetadataResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemCountField;
        
        private string itemNamesSizeBytesField;
        
        private string attributeNameCountField;
        
        private string attributeNamesSizeBytesField;
        
        private string attributeValueCountField;
        
        private string attributeValuesSizeBytesField;
        
        private string timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ItemCount {
            get {
                return this.itemCountField;
            }
            set {
                this.itemCountField = value;
                this.RaisePropertyChanged("ItemCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ItemNamesSizeBytes {
            get {
                return this.itemNamesSizeBytesField;
            }
            set {
                this.itemNamesSizeBytesField = value;
                this.RaisePropertyChanged("ItemNamesSizeBytes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AttributeNameCount {
            get {
                return this.attributeNameCountField;
            }
            set {
                this.attributeNameCountField = value;
                this.RaisePropertyChanged("AttributeNameCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AttributeNamesSizeBytes {
            get {
                return this.attributeNamesSizeBytesField;
            }
            set {
                this.attributeNamesSizeBytesField = value;
                this.RaisePropertyChanged("AttributeNamesSizeBytes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AttributeValueCount {
            get {
                return this.attributeValueCountField;
            }
            set {
                this.attributeValueCountField = value;
                this.RaisePropertyChanged("AttributeValueCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AttributeValuesSizeBytes {
            get {
                return this.attributeValuesSizeBytesField;
            }
            set {
                this.attributeValuesSizeBytesField = value;
                this.RaisePropertyChanged("AttributeValuesSizeBytes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DomainMetadataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.DomainMetadata DomainMetadata;
        
        public DomainMetadataRequest() {
        }
        
        public DomainMetadataRequest(Iris.SimpleDb.Adapter.ServiceRef.DomainMetadata DomainMetadata) {
            this.DomainMetadata = DomainMetadata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DomainMetadataResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.DomainMetadataResponse DomainMetadataResponse;
        
        public DomainMetadataResponse1() {
        }
        
        public DomainMetadataResponse1(Iris.SimpleDb.Adapter.ServiceRef.DomainMetadataResponse DomainMetadataResponse) {
            this.DomainMetadataResponse = DomainMetadataResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class DeleteDomain : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string domainNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
                this.RaisePropertyChanged("DomainName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class DeleteDomainResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
                this.RaisePropertyChanged("ResponseMetadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDomainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.DeleteDomain DeleteDomain;
        
        public DeleteDomainRequest() {
        }
        
        public DeleteDomainRequest(Iris.SimpleDb.Adapter.ServiceRef.DeleteDomain DeleteDomain) {
            this.DeleteDomain = DeleteDomain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDomainResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.DeleteDomainResponse DeleteDomainResponse;
        
        public DeleteDomainResponse1() {
        }
        
        public DeleteDomainResponse1(Iris.SimpleDb.Adapter.ServiceRef.DeleteDomainResponse DeleteDomainResponse) {
            this.DeleteDomainResponse = DeleteDomainResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class PutAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string domainNameField;
        
        private string itemNameField;
        
        private ReplaceableAttribute[] attributeField;
        
        private UpdateCondition expectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
                this.RaisePropertyChanged("DomainName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
                this.RaisePropertyChanged("ItemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute", Order=2)]
        public ReplaceableAttribute[] Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
                this.RaisePropertyChanged("Attribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public UpdateCondition Expected {
            get {
                return this.expectedField;
            }
            set {
                this.expectedField = value;
                this.RaisePropertyChanged("Expected");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class PutAttributesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
                this.RaisePropertyChanged("ResponseMetadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutAttributesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.PutAttributes PutAttributes;
        
        public PutAttributesRequest() {
        }
        
        public PutAttributesRequest(Iris.SimpleDb.Adapter.ServiceRef.PutAttributes PutAttributes) {
            this.PutAttributes = PutAttributes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutAttributesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.PutAttributesResponse PutAttributesResponse;
        
        public PutAttributesResponse1() {
        }
        
        public PutAttributesResponse1(Iris.SimpleDb.Adapter.ServiceRef.PutAttributesResponse PutAttributesResponse) {
            this.PutAttributesResponse = PutAttributesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class BatchPutAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string domainNameField;
        
        private ReplaceableItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
                this.RaisePropertyChanged("DomainName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Order=1)]
        public ReplaceableItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class BatchPutAttributesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
                this.RaisePropertyChanged("ResponseMetadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchPutAttributesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.BatchPutAttributes BatchPutAttributes;
        
        public BatchPutAttributesRequest() {
        }
        
        public BatchPutAttributesRequest(Iris.SimpleDb.Adapter.ServiceRef.BatchPutAttributes BatchPutAttributes) {
            this.BatchPutAttributes = BatchPutAttributes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchPutAttributesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.BatchPutAttributesResponse BatchPutAttributesResponse;
        
        public BatchPutAttributesResponse1() {
        }
        
        public BatchPutAttributesResponse1(Iris.SimpleDb.Adapter.ServiceRef.BatchPutAttributesResponse BatchPutAttributesResponse) {
            this.BatchPutAttributesResponse = BatchPutAttributesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class GetAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string domainNameField;
        
        private string itemNameField;
        
        private string[] attributeNameField;
        
        private bool consistentReadField;
        
        public GetAttributes() {
            this.consistentReadField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
                this.RaisePropertyChanged("DomainName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
                this.RaisePropertyChanged("ItemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeName", Order=2)]
        public string[] AttributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
                this.RaisePropertyChanged("AttributeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ConsistentRead {
            get {
                return this.consistentReadField;
            }
            set {
                this.consistentReadField = value;
                this.RaisePropertyChanged("ConsistentRead");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class GetAttributesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Attribute[] getAttributesResultField;
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Attribute[] GetAttributesResult {
            get {
                return this.getAttributesResultField;
            }
            set {
                this.getAttributesResultField = value;
                this.RaisePropertyChanged("GetAttributesResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
                this.RaisePropertyChanged("ResponseMetadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttributesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.GetAttributes GetAttributes;
        
        public GetAttributesRequest() {
        }
        
        public GetAttributesRequest(Iris.SimpleDb.Adapter.ServiceRef.GetAttributes GetAttributes) {
            this.GetAttributes = GetAttributes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttributesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.GetAttributesResponse GetAttributesResponse;
        
        public GetAttributesResponse1() {
        }
        
        public GetAttributesResponse1(Iris.SimpleDb.Adapter.ServiceRef.GetAttributesResponse GetAttributesResponse) {
            this.GetAttributesResponse = GetAttributesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class DeleteAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string domainNameField;
        
        private string itemNameField;
        
        private Attribute[] attributeField;
        
        private UpdateCondition expectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
                this.RaisePropertyChanged("DomainName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
                this.RaisePropertyChanged("ItemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute", Order=2)]
        public Attribute[] Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
                this.RaisePropertyChanged("Attribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public UpdateCondition Expected {
            get {
                return this.expectedField;
            }
            set {
                this.expectedField = value;
                this.RaisePropertyChanged("Expected");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class DeleteAttributesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
                this.RaisePropertyChanged("ResponseMetadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAttributesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.DeleteAttributes DeleteAttributes;
        
        public DeleteAttributesRequest() {
        }
        
        public DeleteAttributesRequest(Iris.SimpleDb.Adapter.ServiceRef.DeleteAttributes DeleteAttributes) {
            this.DeleteAttributes = DeleteAttributes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAttributesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.DeleteAttributesResponse DeleteAttributesResponse;
        
        public DeleteAttributesResponse1() {
        }
        
        public DeleteAttributesResponse1(Iris.SimpleDb.Adapter.ServiceRef.DeleteAttributesResponse DeleteAttributesResponse) {
            this.DeleteAttributesResponse = DeleteAttributesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class BatchDeleteAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string domainNameField;
        
        private DeleteableItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
                this.RaisePropertyChanged("DomainName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Order=1)]
        public DeleteableItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class BatchDeleteAttributesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
                this.RaisePropertyChanged("ResponseMetadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchDeleteAttributesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.BatchDeleteAttributes BatchDeleteAttributes;
        
        public BatchDeleteAttributesRequest() {
        }
        
        public BatchDeleteAttributesRequest(Iris.SimpleDb.Adapter.ServiceRef.BatchDeleteAttributes BatchDeleteAttributes) {
            this.BatchDeleteAttributes = BatchDeleteAttributes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchDeleteAttributesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.BatchDeleteAttributesResponse BatchDeleteAttributesResponse;
        
        public BatchDeleteAttributesResponse1() {
        }
        
        public BatchDeleteAttributesResponse1(Iris.SimpleDb.Adapter.ServiceRef.BatchDeleteAttributesResponse BatchDeleteAttributesResponse) {
            this.BatchDeleteAttributesResponse = BatchDeleteAttributesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class Select : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string selectExpressionField;
        
        private string nextTokenField;
        
        private bool consistentReadField;
        
        public Select() {
            this.consistentReadField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SelectExpression {
            get {
                return this.selectExpressionField;
            }
            set {
                this.selectExpressionField = value;
                this.RaisePropertyChanged("SelectExpression");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NextToken {
            get {
                return this.nextTokenField;
            }
            set {
                this.nextTokenField = value;
                this.RaisePropertyChanged("NextToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ConsistentRead {
            get {
                return this.consistentReadField;
            }
            set {
                this.consistentReadField = value;
                this.RaisePropertyChanged("ConsistentRead");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class SelectResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SelectResult selectResultField;
        
        private ResponseMetadata responseMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SelectResult SelectResult {
            get {
                return this.selectResultField;
            }
            set {
                this.selectResultField = value;
                this.RaisePropertyChanged("SelectResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseMetadata ResponseMetadata {
            get {
                return this.responseMetadataField;
            }
            set {
                this.responseMetadataField = value;
                this.RaisePropertyChanged("ResponseMetadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdb.amazonaws.com/doc/2009-04-15/")]
    public partial class SelectResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Item[] itemField;
        
        private string nextTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Order=0)]
        public Item[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NextToken {
            get {
                return this.nextTokenField;
            }
            set {
                this.nextTokenField = value;
                this.RaisePropertyChanged("NextToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.Select Select;
        
        public SelectRequest() {
        }
        
        public SelectRequest(Iris.SimpleDb.Adapter.ServiceRef.Select Select) {
            this.Select = Select;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdb.amazonaws.com/doc/2009-04-15/", Order=0)]
        public Iris.SimpleDb.Adapter.ServiceRef.SelectResponse SelectResponse;
        
        public SelectResponse1() {
        }
        
        public SelectResponse1(Iris.SimpleDb.Adapter.ServiceRef.SelectResponse SelectResponse) {
            this.SelectResponse = SelectResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AmazonSDBPortTypeChannel : Iris.SimpleDb.Adapter.ServiceRef.AmazonSDBPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AmazonSDBPortTypeClient : System.ServiceModel.ClientBase<Iris.SimpleDb.Adapter.ServiceRef.AmazonSDBPortType>, Iris.SimpleDb.Adapter.ServiceRef.AmazonSDBPortType {
        
        public AmazonSDBPortTypeClient() {
        }
        
        public AmazonSDBPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AmazonSDBPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmazonSDBPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AmazonSDBPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Iris.SimpleDb.Adapter.ServiceRef.CreateDomainResponse1 CreateDomain(Iris.SimpleDb.Adapter.ServiceRef.CreateDomainRequest request) {
            return base.Channel.CreateDomain(request);
        }
        
        public Iris.SimpleDb.Adapter.ServiceRef.ListDomainsResponse1 ListDomains(Iris.SimpleDb.Adapter.ServiceRef.ListDomainsRequest request) {
            return base.Channel.ListDomains(request);
        }
        
        public Iris.SimpleDb.Adapter.ServiceRef.DomainMetadataResponse1 DomainMetadata(Iris.SimpleDb.Adapter.ServiceRef.DomainMetadataRequest request) {
            return base.Channel.DomainMetadata(request);
        }
        
        public Iris.SimpleDb.Adapter.ServiceRef.DeleteDomainResponse1 DeleteDomain(Iris.SimpleDb.Adapter.ServiceRef.DeleteDomainRequest request) {
            return base.Channel.DeleteDomain(request);
        }
        
        public Iris.SimpleDb.Adapter.ServiceRef.PutAttributesResponse1 PutAttributes(Iris.SimpleDb.Adapter.ServiceRef.PutAttributesRequest request) {
            return base.Channel.PutAttributes(request);
        }
        
        public Iris.SimpleDb.Adapter.ServiceRef.BatchPutAttributesResponse1 BatchPutAttributes(Iris.SimpleDb.Adapter.ServiceRef.BatchPutAttributesRequest request) {
            return base.Channel.BatchPutAttributes(request);
        }
        
        public Iris.SimpleDb.Adapter.ServiceRef.GetAttributesResponse1 GetAttributes(Iris.SimpleDb.Adapter.ServiceRef.GetAttributesRequest request) {
            return base.Channel.GetAttributes(request);
        }
        
        public Iris.SimpleDb.Adapter.ServiceRef.DeleteAttributesResponse1 DeleteAttributes(Iris.SimpleDb.Adapter.ServiceRef.DeleteAttributesRequest request) {
            return base.Channel.DeleteAttributes(request);
        }
        
        public Iris.SimpleDb.Adapter.ServiceRef.BatchDeleteAttributesResponse1 BatchDeleteAttributes(Iris.SimpleDb.Adapter.ServiceRef.BatchDeleteAttributesRequest request) {
            return base.Channel.BatchDeleteAttributes(request);
        }
        
        public Iris.SimpleDb.Adapter.ServiceRef.SelectResponse1 Select(Iris.SimpleDb.Adapter.ServiceRef.SelectRequest request) {
            return base.Channel.Select(request);
        }
    }
}
